-module(erlmd_tests).

-include_lib("eunit/include/eunit.hrl").

unit_test_() -> 
    [
     ?_assertEqual("<p>=></p>", erlmd:conv("=>")),
     ?_assertEqual("<blockquote>\n  <p>=</p>\n</blockquote>", erlmd:conv(">=")),
     ?_assertEqual("<p>=&lt;</p>", erlmd:conv("=<")),
     ?_assertEqual("<p>&lt;=</p>", erlmd:conv("<=")),
     ?_assertEqual("<p>&lt;></p>", erlmd:conv("<>")),
     % ?_assertEqual("<p><flame on>\nblah\n</flame off>\n<bingo>\n<bingo master></p>", erlmd:conv("<flame on>\nblah\n</flame off>\n<bingo>\n<bingo master>")),
     % ?_assertEqual("<p><flame on>\n</flame on></p>", erlmd:conv("<flame on>\n</flame on>")),
     ?_assertEqual("<p><flame on></p>", erlmd:conv("<flame on>")),
     ?_assertEqual("<table>\n<img src=\"http://example.com\">\n</table>", erlmd:conv("<table>\n<img src=\"http://example.com\">\n</table>")),
     % ?_assertEqual("<table>\n<tr>\n<td>\n***FAQ*** - *WTF?* Postal Chess Records is a mash-up between Postal Chess and Chess Records where two Record Selectors slug it out over the interwebs in a sonic-soundclash, duh!\n</td>\n<td>\n<img src=\"http://imgur.com/VmdEL.png\">\n</td>\n</tr>\n</table>", erlmd:conv("<table>\n<tr>\n<td>\n***FAQ*** - *WTF?* Postal Chess Records is a mash-up between Postal Chess and Chess Records where two Record Selectors slug it out over the interwebs in a sonic-soundclash, duh!\n</td>\n<td>\n<img src=\"http://imgur.com/VmdEL.png\">\n</td>\n</tr>\n</table>")),
     % ?_assertEqual("<form action=\"https://checkout.google.com/api/checkout/v2/\ncheckoutForm/Merchant/960226209420618\" id=\"BB_BuyButtonForm\"\nmethod=\"post\" name=\"BB_BuyButtonForm\" target=\"_top\">\n<input name=\"item_name_1\" type=\"hidden\" value=\"Premium\nHypernumbers Account\"/><input name=\"item_description_1\" \ntype=\"hidden\" value=\"Premium Hypernumbers Account\"/>\n<input name=\"item_quantity_1\" type=\"hidden\" value=\"1\"/>\n<input name=\"item_price_1\" type=\"hidden\" value=\"90.0\"/>\n<input name=\"item_currency_1\" type=\"hidden\" value=\"GBP\"/>\n<input name=\"_charset_\" type=\"hidden\" value=\"utf-8\"/>\n<input alt=\"\" src=\"https://checkout.google.com/buttons/buy.gif?\nmerchant_id=960226209420618&amp;w=117&amp;h=48&amp;style=white&amp;\nvariant=text&amp;loc=en_US\" type=\"image\"/></form>", erlmd:conv("<form action=\"https://checkout.google.com/api/checkout/v2/\ncheckoutForm/Merchant/960226209420618\" id=\"BB_BuyButtonForm\"\nmethod=\"post\" name=\"BB_BuyButtonForm\" target=\"_top\">\n<input name=\"item_name_1\" type=\"hidden\" value=\"Premium\nHypernumbers Account\"/><input name=\"item_description_1\" \ntype=\"hidden\" value=\"Premium Hypernumbers Account\"/>\n<input name=\"item_quantity_1\" type=\"hidden\" value=\"1\"/>\n<input name=\"item_price_1\" type=\"hidden\" value=\"90.0\"/>\n<input name=\"item_currency_1\" type=\"hidden\" value=\"GBP\"/>\n<input name=\"_charset_\" type=\"hidden\" value=\"utf-8\"/>\n<input alt=\"\" src=\"https://checkout.google.com/buttons/buy.gif?\nmerchant_id=960226209420618&amp;w=117&amp;h=48&amp;style=white&amp;\nvariant=text&amp;loc=en_US\" type=\"image\"/></form>\n")),
     ?_assertEqual("<pre><code>[1 -1] [-1 1]\n</code></pre>", erlmd:conv("\t[1 -1] [-1 1]")),
     ?_assertEqual("<pre><code>f_s/1, t_s/2\n</code></pre>", erlmd:conv("\tf_s/1, t_s/2")),
     ?_assertEqual("<pre><code>a\n\nb\n</code></pre>", erlmd:conv("\ta\n\n\tb")),
     ?_assertEqual("<pre><code>[a]\n</code></pre>", erlmd:conv("    [a]")),
     ?_assertEqual("<p>[a]</p>", erlmd:conv("   [a]")),
     ?_assertEqual("<p>[a]</p>", erlmd:conv("  [a]")),
     ?_assertEqual("<pre><code>def positive = {\n    0 &lt; it\n}\n</code></pre>", erlmd:conv("    def positive = {\n        0 < it\n    }")),
     ?_assertEqual("<h3>\nLets let html through\n</h3>", erlmd:conv("<h3>\nLets let html through\n</h3>")),
     ?_assertEqual("<p>&copy;</p>", erlmd:conv("&copy;")),
     ?_assertEqual("<h3 id='test'>\nLets let html through\n</h3>", erlmd:conv("<h3 id='test'>\nLets let html through\n</h3>")),
     ?_assertEqual("<p><img src=\"_underscore\" alt=\"login\" title=\"\" /></p>", erlmd:conv("![login](_underscore)")),
     ?_assertEqual("<p><a href=\"_underscore\">login</a></p>", erlmd:conv("[login](_underscore)")),
     ?_assertEqual("<ol>\n<li>should be <em>italic</em></li>\n<li>should be <strong>bold</strong></li>\n<li>should be <strong><em>bold italic</em></strong></li>\n</ol>", erlmd:conv("\n 1.   should be *italic*\n 2.  should be **bold**\n 3.  should be ***bold italic***")),
     ?_assertEqual("<ul>\n<li>should be <em>italic</em></li>\n<li>should be <strong>bold</strong></li>\n<li>should be <strong><em>bold italic</em></strong></li>\n</ul>", erlmd:conv("\n - should be *italic*\n - should be **bold**\n - should be ***bold italic***")),
     ?_assertEqual("<p>some stuff <code>yaycode</code> more stuff <code>more code!</code></p>", erlmd:conv("some stuff `yaycode` more stuff `more code!`")),
     ?_assertEqual("<p><a href=\"http://example.com/some/link\"><img src=\"/img/somebutton.png\" alt=\"Button\" title=\"\" /></a></p>", erlmd:conv("[![Button](/img/somebutton.png)](http://example.com/some/link)")),
     ?_assertEqual("<pre><code>alice\nbob\n</code></pre>\n\n<p>chaz</p>", erlmd:conv("    alice\n    bob\nchaz")),
     ?_assertEqual("<blockquote>\n  <p>alice\n<br /> bob\n<br /> chaz</p>\n</blockquote>", erlmd:conv("> alice\n> bob\n> chaz")),
     ?_assertEqual("<blockquote>\n  <p>alice\n<br /> \n<br /> bob\n<br /> chaz</p>\n</blockquote>", erlmd:conv("> alice\n> \n> bob\n> chaz")),
     % Blockquote with hard line break (two trailing spaces) - AST correctly converts to <br />
     ?_assertEqual("<blockquote>\n  <p>alice <br />\n<br /> bob</p>\n</blockquote>", erlmd:conv("> alice  \n> bob")),
     ?_assertEqual("<ul>\n<li>a</li>\n<li>b</li>\n</ul>", erlmd:conv(" - a\n - b\n")),
     ?_assertEqual("<ol>\n<li>a</li>\n<li>b</li>\n</ol>", erlmd:conv(" 1. a\n 2. b\n")),
     ?_assertEqual("<p>blah <img src=\"http://example.com\" alt=\"blah\" title=\"title\" /> blah</p>", erlmd:conv("blah ![blah][1] blah\n\n\n  [1]: http://example.com (title)")),
     ?_assertEqual("<p>blah <img src=\"http://example.com\" alt=\"blah\" title=\"title\" /> blah</p>", erlmd:conv("blah ![blah][1] blah\n\n\n  [1]: http://example.com \"title\"")),
     ?_assertEqual("<p>blah <img src=\"http://example.com\" alt=\"blah\" title=\"\" /> blah</p>", erlmd:conv("blah ![blah][1] blah\n\n\n  [1]: http://example.com")),
     ?_assertEqual("<p>Now is the winter of <code>our discontent</code> made glorious summer by this Son of York</p>", erlmd:conv("Now is the winter of `our discontent` made glorious summer by this Son of York")),
     ?_assertEqual("<p>blah <a href=\"http://example.com\" title=\"title\">blah</a> blah</p>", erlmd:conv("blah [blah][1] blah\n\n\n  [1]: http://example.com (title)")),
     ?_assertEqual("<p>blah <a href=\"http://example.com\" title=\"title\">blah</a> blah</p>", erlmd:conv("blah [blah][1] blah\n\n\n  [1]: http://example.com \"title\"")),
     ?_assertEqual("<p>blah <a href=\"http://example.com\">blah</a> blah</p>", erlmd:conv("blah [blah][1] blah\n\n\n  [1]: http://example.com")),
     ?_assertEqual("<h2>> blah</h2>", erlmd:conv("> blah\n-------------")),
     ?_assertEqual("", erlmd:conv("  \n")),
     ?_assertEqual("<p><img src=\"http://example.com\" alt=\"alt text\" title=\"\" /></p>", erlmd:conv("![alt text][1]\n\n[1]: http://example.com")),
     ?_assertEqual("<p><img src=\"http://example.com\" alt=\"alt text\" title=\"optional title\" /></p>", erlmd:conv("![alt text][1]\n\n[1]: http://example.com \"optional title\"")),
     ?_assertEqual("<p><a href=\"http://example.com\">link text</a></p>", erlmd:conv("[link text][1]\n\n[1]: http://example.com")),
     ?_assertEqual("<p><a href=\"http://example.com\" title=\"optional title\">link text</a></p>", erlmd:conv("[link text][1]\n\n[1]: http://example.com \"optional title\"")),
     ?_assertEqual("<p>blah</p>\n\n<p>bleh</p>", erlmd:conv("blah\n\n\nbleh")),
     ?_assertEqual("<p><code>&lt;div&gt;blah&lt;/div&gt;</code></p>", erlmd:conv("`<div>blah</div>`")),
     ?_assertEqual("<p>My <a href=\"http://example.com\">link</a> test</p>", erlmd:conv("My [link][id] test\n[id]: http://example.com")),
     ?_assertEqual("<p>My <a href=\"http://example.com\">id</a> test</p>", erlmd:conv("My [id] test\n[id]: http://example.com")),
     ?_assertEqual("<p>blah <a href=\"https://something.com:1234/a/path\">https://something.com:1234/a/path</a> blah\na</p>", erlmd:conv("blah <https://something.com:1234/a/path> blah\na")),
     ?_assertEqual("<p>blah <a href=\"http://something.com:1234/a/path\">http://something.com:1234/a/path</a> blah\na</p>", erlmd:conv("blah <http://something.com:1234/a/path> blah\na")),
     ?_assertEqual("<p>Some text <img src=\"/a/path\" alt=\"hey\" title=\"\" /> there\na</p>", erlmd:conv("[id]: /a/path\nSome text ![hey] [id] there\na")),
     ?_assertEqual("<p>Some text <img src=\"/a/path\" alt=\"hey\" title=\"\" /> there\na</p>", erlmd:conv("[id]: /a/path\nSome text ![hey][id] there\na")),
     ?_assertEqual("<p>Some text <a href=\"/a/path\">hey</a> there\na</p>", erlmd:conv("[id]:   \t \t   /a/path\nSome text [hey][id] there\na")),
     ?_assertEqual("<p>Some text [id] there\na</p>", erlmd:conv("[id]: /a/path\nSome text \\[id] there\na")),
     ?_assertEqual("<p>Some text <a href=\"/a/path\">hey</a> there\na</p>", erlmd:conv("[id]: /a/path\nSome text [hey] [id] there\na")),
     ?_assertEqual("<p>Some text <a href=\"/a/path\">hey</a> there\na</p>", erlmd:conv("[id]: /a/path\nSome text [hey][id] there\na")),
     ?_assertEqual("<p>an <img src=\"path/jpg.jpg\" alt=\"\" title=\"\" /> image\na</p>", erlmd:conv("an ![](path/jpg.jpg ) image\na")),
     ?_assertEqual("<p>an <img src=\"path/jpg.jpg\" alt=\"Alt\" title=\"\" /> image\na</p>", erlmd:conv("an ![Alt](path/jpg.jpg ) image\na")),
     ?_assertEqual("<p>an <img src=\"path/jpg.jpg\" alt=\"Alt\" title=\"Title\" /> image\na</p>", erlmd:conv("an ![Alt](path/jpg.jpg 'Title') image\na")),
     ?_assertEqual("<p>an <img src=\"path/jpg.jpg\" alt=\"Alt\" title=\"Title\" /> image\na</p>", erlmd:conv("an ![Alt](path/jpg.jpg \"Title\") image\na")),
     ?_assertEqual("<p>an <img src=\"path/jpg.jpg\" alt=\"Alt\" title=\"Title\" /> image\na</p>", erlmd:conv("an ![Alt] (path/jpg.jpg \"Title\") image\na")),
     ?_assertEqual("<p>An <a href=\"http://example.com/\">example</a> of link\na</p>", erlmd:conv("An [example](http://example.com/) of link\na")),
     ?_assertEqual("<p>An <a href=\"http://example.com/\" title=\"Title\"></a> of link\na</p>", erlmd:conv("An [](http://example.com/ \"Title\") of link\na")),
     ?_assertEqual("<p>An <a href=\"http://example.com/\" title=\"Title\">example</a> of link\na</p>", erlmd:conv("An [example](http://example.com/ 'Title') of link\na")),
     ?_assertEqual("<p>An <a href=\"http://example.com/\" title=\"Title\">example</a> of link\na</p>", erlmd:conv("An [example](http://example.com/ \"Title\") of link\na")),
     ?_assertEqual("<p>An [example] (http://example.com/ \"Title\") of link\na</p>", erlmd:conv("An [example] (http://example.com/ \"Title\") of link\na")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n   [id]: /example.com")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n   [id]: http://example.com")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n[id]: <http://example.com>")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n[id]: http://example.com")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n[id]: http://example.com (Title)")),
     ?_assertEqual("<p>a\na</p>", erlmd:conv("a\na\n[id]: http://example.com \"Title\"")),
     ?_assertEqual("<p><em>_</em>blah\na</p>", erlmd:conv("___blah\na")),
     ?_assertEqual("<p>---blah\na</p>", erlmd:conv("---blah\na")),
     ?_assertEqual("<p><em>*</em>blah\na</p>", erlmd:conv("***blah\na")),
     ?_assertEqual("<hr />", erlmd:conv("_ _ _")),
     ?_assertEqual("<hr />", erlmd:conv("- - -")),
     ?_assertEqual("<hr />", erlmd:conv("* * *")),
     ?_assertEqual("<hr />", erlmd:conv("_____")),
     ?_assertEqual("<hr />", erlmd:conv("-----")),
     ?_assertEqual("<hr />", erlmd:conv("*****")),
     ?_assertEqual("<hr />", erlmd:conv("___")),
     ?_assertEqual("<hr />", erlmd:conv("---")),
     ?_assertEqual("<hr />", erlmd:conv("***")),
     ?_assertEqual("<pre><code>&lt;div&gt;&amp;\n</code></pre>", erlmd:conv("\t<div>&")),
     ?_assertEqual("<pre><code>&lt;div&gt;\n</code></pre>", erlmd:conv("\t<div>")),
     ?_assertEqual("<ul>\n<li>a\n    b</li>\n</ul>", erlmd:conv("+ a\n\t\tb")),
     ?_assertEqual("<ul>\n<li>a\n    b</li>\n</ul>", erlmd:conv("+ a\n  \t  b")),
     ?_assertEqual("<ul>\n<li>a\n    b</li>\n</ul>", erlmd:conv("+ a\n\t    b")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", erlmd:conv("\tb\n\n\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", erlmd:conv("\tb\n\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", erlmd:conv("\tb\n\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", erlmd:conv("\tb\n\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>\n\n<p>c</p>", erlmd:conv("\tb\nc")),
     ?_assertEqual("<pre><code>b\n</code></pre>", erlmd:conv("\tb")),
     ?_assertEqual("<pre><code>b\n</code></pre>", erlmd:conv("    b")),
     ?_assertEqual("<ol>\n<li><p>a</p></li>\n<li><p>b</p></li>\n<li><p>c</p></li>\n</ol>", erlmd:conv("4. a\n\n5. b\n\n6. c")),
     ?_assertEqual("<ol>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n</ol>", erlmd:conv("4. a\n5. b\n6. c")),
     ?_assertEqual("<ol>\n<li>blah\nblah</li>\n</ol>", erlmd:conv("4. blah\nblah")),
     ?_assertEqual("<p>555.blah\na</p>", erlmd:conv("555.blah\na")),
     ?_assertEqual("<p>555 @blah\na</p>", erlmd:conv("555 @blah\na")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", erlmd:conv("555. blah")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", erlmd:conv("4. blah")),
     ?_assertEqual("<ol>\n<li>blah</li>\n</ol>", erlmd:conv("1. blah")),
     ?_assertEqual("<ul>\n<li>blah\nblah</li>\n</ul>", erlmd:conv("- blah\nblah")),
     ?_assertEqual("<ul>\n<li><p>a</p></li>\n<li><p>b</p></li>\n<li><p>c</p></li>\n<li>d</li>\n</ul>", erlmd:conv("- a\n\n+ b\n\n+ c\n* d")),
     ?_assertEqual("<ul>\n<li><p>a</p></li>\n<li><p>b</p></li>\n</ul>", erlmd:conv("- a\n\n+ b")),
     ?_assertEqual("<ul>\n<li><p>a</p>\n\n<p>XX+ b</p></li>\n</ul>", erlmd:conv("- a\n\n \n\t\n XX+ b")),
     ?_assertEqual("<ul>\n<li><p>a</p>\n\n<p>XX+ b</p></li>\n</ul>", erlmd:conv("- a\n \n \n\t\n XX+ b")),
     ?_assertEqual("<ul>\n<li><p>a</p>\n\n<p>XX+ b</p></li>\n</ul>", erlmd:conv("- a\n\n\n\n XX+ b")),
     ?_assertEqual("<ul>\n<li>a</li>\n</ul>\n\n<p>XX+ b</p>", erlmd:conv("- a\n\n\n\nXX+ b")),
     ?_assertEqual("<ul>\n<li>a</li>\n<li>b</li>\n<li>c</li>\n</ul>", erlmd:conv("- a\n+ b\n- c")),
     ?_assertEqual("<p>-blah\na</p>", erlmd:conv("-blah\na")),
     ?_assertEqual("<ul>\n<li>blah</li>\n</ul>", erlmd:conv("- blah")),
     ?_assertEqual("<p>*blah\na</p>", erlmd:conv("*blah\na")),
     ?_assertEqual("<ul>\n<li>blah</li>\n</ul>", erlmd:conv("* blah")),
     ?_assertEqual("<p>+blah\na</p>", erlmd:conv("+blah\na")),
     ?_assertEqual("<ul>\n<li>blah</li>\n</ul>", erlmd:conv("+ blah")),
     ?_assertEqual("<p>bleh</p>\n\n<blockquote>\n  <p>blah</p>\n</blockquote>", erlmd:conv("bleh\n> blah")),
     ?_assertEqual("<blockquote>\n  <p>blah\na</p>\n</blockquote>", erlmd:conv("> blah\na")),
     ?_assertEqual("<h1>blahblah</h1>\n\n<p>bleh</p>", erlmd:conv("# blahblah ###\nbleh")),
     ?_assertEqual("<h6># blahblah</h6>\n\n<p>bleh</p>", erlmd:conv("####### blahblah\nbleh")),
     ?_assertEqual("<h6>blahblah</h6>\n\n<p>bleh</p>", erlmd:conv("###### blahblah\nbleh")),
     ?_assertEqual("<h5>blahblah</h5>\n\n<p>bleh</p>", erlmd:conv("##### blahblah\nbleh")),
     ?_assertEqual("<h4>blahblah</h4>\n\n<p>bleh</p>", erlmd:conv("#### blahblah\nbleh")),
     ?_assertEqual("<h3>blahblah</h3>\n\n<p>bleh</p>", erlmd:conv("### blahblah\nbleh")),
     ?_assertEqual("<h2>blahblah</h2>\n\n<p>bleh</p>", erlmd:conv("## blahblah\nbleh")),
     ?_assertEqual("<h1>blahblah</h1>\n\n<p>bleh</p>", erlmd:conv("# blahblah\nbleh")),
     ?_assertEqual("<h1>blahblah</h1>", erlmd:conv("# blahblah ###")),
     ?_assertEqual("<h6># blahblah</h6>", erlmd:conv("####### blahblah")),
     ?_assertEqual("<h6>blahblah</h6>", erlmd:conv("###### blahblah")),
     ?_assertEqual("<h5>blahblah</h5>", erlmd:conv("##### blahblah")),
     ?_assertEqual("<h4>blahblah</h4>", erlmd:conv("#### blahblah")),
     ?_assertEqual("<h3>blahblah</h3>", erlmd:conv("### blahblah")),
     ?_assertEqual("<h2>blahblah</h2>", erlmd:conv("## blahblah")),
     ?_assertEqual("<h1>blahblah</h1>", erlmd:conv("# blahblah")),
     ?_assertEqual("<h2>> a</h2>", erlmd:conv("> a\n-")),
     ?_assertEqual("<h1>> a</h1>", erlmd:conv("> a\n=")),
     ?_assertEqual("<h2>blahblah</h2>\n\n<p>blah</p>", erlmd:conv("blahblah\n-----\nblah")),
     ?_assertEqual("<h1>blahblah</h1>\n\n<p>blah</p>", erlmd:conv("blahblah\n====\nblah")),
     ?_assertEqual("<h2>blahblah</h2>", erlmd:conv("blahblah\n-----")),
     ?_assertEqual("<h1>blahblah</h1>", erlmd:conv("blahblah\n====")),
     ?_assertEqual("<p>blah\nblah</p>", erlmd:conv("blah\r\nblah\n")),
     ?_assertEqual("<p>blah\nblah</p>", erlmd:conv("blah\r\nblah")),
     ?_assertEqual("<p>blah\nblah</p>", erlmd:conv("blah\nblah")),
     ?_assertEqual("<p><strong><em>you</em></strong> sad bastard\na</p>", erlmd:conv("___you___ sad bastard\na")),
     ?_assertEqual("<p><strong>you</strong> sad bastard\na</p>", erlmd:conv("__you__ sad bastard\na")),
     ?_assertEqual("<p><em>you</em> sad bastard\na</p>", erlmd:conv("_you_ sad bastard\na")),
     ?_assertEqual("<p><strong><em>you</em></strong> sad bastard\na</p>", erlmd:conv("***you*** sad bastard\na")),
     ?_assertEqual("<p><strong>you</strong> sad bastard\na</p>", erlmd:conv("**you** sad bastard\na")),
     ?_assertEqual("<p><em>you</em> sad bastard\na</p>", erlmd:conv("*you* sad bastard\na")),
     ?_assertEqual("<p>you _sad_ bastard\na</p>", erlmd:conv("you \\_sad\\_ bastard\na")),
     ?_assertEqual("<p>you *sad* bastard\na</p>", erlmd:conv("you \\*sad\\* bastard\na")),
     ?_assertEqual("<p>you<em>sad</em>bastard\na</p>", erlmd:conv("you_sad_bastard\na")),
     ?_assertEqual("<p>you<em>sad</em>bastard\na</p>", erlmd:conv("you*sad*bastard\na")),
     ?_assertEqual("<p>you <strong><em>sad</em></strong> bastard\na</p>", erlmd:conv("you ___sad___ bastard\na")),
     ?_assertEqual("<p>you <strong>sad</strong> bastard\na</p>", erlmd:conv("you __sad__ bastard\na")),
     ?_assertEqual("<p>you <em>sad</em> bastard\na</p>", erlmd:conv("you _sad_ bastard\na")),
     ?_assertEqual("<p>you <strong><em>sad</em></strong> bastard\na</p>", erlmd:conv("you ***sad*** bastard\na")),
     ?_assertEqual("<p>you <strong>sad</strong> bastard\na</p>", erlmd:conv("you **sad** bastard\na")),
     ?_assertEqual("<p>you <em>sad</em> bastard\na</p>", erlmd:conv("you *sad* bastard\na")),
     ?_assertEqual("<h6>#</h6>\n\n<p>a</p>", erlmd:conv("########\na")),
     ?_assertEqual("<h6>#</h6>\n\n<p>a</p>", erlmd:conv("#######\na")),
     ?_assertEqual("<h5>#</h5>\n\n<p>a</p>", erlmd:conv("######\na")),
     ?_assertEqual("<h4>#</h4>\n\n<p>a</p>", erlmd:conv("#####\na")),
     ?_assertEqual("<h3>#</h3>\n\n<p>a</p>", erlmd:conv("####\na")),
     ?_assertEqual("<h2>#</h2>\n\n<p>a</p>", erlmd:conv("###\na")),
     ?_assertEqual("<h1>#</h1>\n\n<p>a</p>", erlmd:conv("##\na")),
     ?_assertEqual("<p>#\na</p>", erlmd:conv("#\na")),
     ?_assertEqual("<p>[\na</p>", erlmd:conv("\n[\na")),
     ?_assertEqual("<p>>\na</p>", erlmd:conv("\n>\na")),
     ?_assertEqual("<p>-\na</p>", erlmd:conv("\n-\na")),
     ?_assertEqual("<p>=\na</p>", erlmd:conv("\n=\na")),
     ?_assertEqual("<p>[\na</p>", erlmd:conv("[\na")),
     ?_assertEqual("<p>>\na</p>", erlmd:conv(">\na")),
     ?_assertEqual("<p>-\na</p>", erlmd:conv("-\na")),
     ?_assertEqual("<p>=\na</p>", erlmd:conv("=\na")),
     ?_assertEqual("<p>abc`def\na</p>", erlmd:conv("abc\\`def\na")),
     ?_assertEqual("<p>xyz\nab:c\na</p>", erlmd:conv("xyz\r\nab:c\na")),
     ?_assertEqual("<p>xyz\nab:c\na</p>", erlmd:conv("xyz\nab:c\na")),
     ?_assertEqual("<p>xyz    ab:c\na</p>", erlmd:conv("xyz\tab:c\na")),
     ?_assertEqual("<p>xyz ab:c\na</p>", erlmd:conv("xyz ab:c\na")),
     ?_assertEqual("<p>xyz(ab:c\na</p>", erlmd:conv("xyz(ab:c\na")),
     ?_assertEqual("<p>xyz]ab:c\na</p>", erlmd:conv("xyz]ab:c\na")),
     ?_assertEqual("<p>xyz[ab:c\na</p>", erlmd:conv("xyz[ab:c\na")),
     ?_assertEqual("<p>xyz)ab:c\na</p>", erlmd:conv("xyz)ab:c\na")),
     ?_assertEqual("<p>xyz(ab:c\na</p>", erlmd:conv("xyz(ab:c\na")),
     ?_assertEqual("<p>xyz/ab:c\na</p>", erlmd:conv("xyz/ab:c\na")),
     ?_assertEqual("<p>xyz\\ab:c\na</p>", erlmd:conv("xyz\\ab:c\na")),
     ?_assertEqual("<p>xyz!ab:c\na</p>", erlmd:conv("xyz!ab:c\na")),
     ?_assertEqual("<p>xyz`ab:c\na</p>", erlmd:conv("xyz`ab:c\na")),
     ?_assertEqual("<p>xyz\"ab:c\na</p>", erlmd:conv("xyz\"ab:c\na")),
     ?_assertEqual("<p>xyz'ab:c\na</p>", erlmd:conv("xyz'ab:c\na")),
     ?_assertEqual("<p>xyz:ab:c\na</p>", erlmd:conv("xyz:ab:c\na")),
     ?_assertEqual("<p>xyz.ab:c\na</p>", erlmd:conv("xyz.ab:c\na")),
     ?_assertEqual("<p>xyz0ab:c\na</p>", erlmd:conv("xyz0ab:c\na")),
     ?_assertEqual("<p>xyz9ab:c\na</p>", erlmd:conv("xyz9ab:c\na")),
     ?_assertEqual("<p>xyz8ab:c\na</p>", erlmd:conv("xyz8ab:c\na")),
     ?_assertEqual("<p>xyz7ab:c\na</p>", erlmd:conv("xyz7ab:c\na")),
     ?_assertEqual("<p>xyz6ab:c\na</p>", erlmd:conv("xyz6ab:c\na")),
     ?_assertEqual("<p>xyz5ab:c\na</p>", erlmd:conv("xyz5ab:c\na")),
     ?_assertEqual("<p>xyz4ab:c\na</p>", erlmd:conv("xyz4ab:c\na")),
     ?_assertEqual("<p>xyz3ab:c\na</p>", erlmd:conv("xyz3ab:c\na")),
     ?_assertEqual("<p>xyz2ab:c\na</p>", erlmd:conv("xyz2ab:c\na")),
     ?_assertEqual("<p>xyz1ab:c\na</p>", erlmd:conv("xyz1ab:c\na")),
     ?_assertEqual("<p>xyz_ab:c\na</p>", erlmd:conv("xyz_ab:c\na")),
     ?_assertEqual("<p>xyz*ab:c\na</p>", erlmd:conv("xyz*ab:c\na")),
     ?_assertEqual("<p>xyz+ab:c\na</p>", erlmd:conv("xyz+ab:c\na")),
     ?_assertEqual("<p>xyz>ab:c\na</p>", erlmd:conv("xyz>ab:c\na")),
     ?_assertEqual("<p>xyz#ab:c\na</p>", erlmd:conv("xyz#ab:c\na")),
     ?_assertEqual("<p>xyz-ab:c\na</p>", erlmd:conv("xyz-ab:c\na")),
     ?_assertEqual("<p>xyz=ab:c\na</p>", erlmd:conv("xyz=ab:c\na")),
     ?_assertEqual("<p>xyz/ab:c\na</p>", erlmd:conv("xyz/ab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv("\r\n ab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv("\n ab:c\na")),
     ?_assertEqual("<pre><code> ab:c\n</code></pre>\n\n<p>a</p>", erlmd:conv("\t ab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv("  ab:c\na")),
     ?_assertEqual("<p>( ab:c\na</p>", erlmd:conv("( ab:c\na")),
     ?_assertEqual("<p>] ab:c\na</p>", erlmd:conv("] ab:c\na")),
     ?_assertEqual("<p>[ ab:c\na</p>", erlmd:conv("[ ab:c\na")),
     ?_assertEqual("<p>) ab:c\na</p>", erlmd:conv(") ab:c\na")),
     ?_assertEqual("<p>( ab:c\na</p>", erlmd:conv("( ab:c\na")),
     ?_assertEqual("<p>/ ab:c\na</p>", erlmd:conv("/ ab:c\na")),
     ?_assertEqual("<p>\\ ab:c\na</p>", erlmd:conv("\\ ab:c\na")),
     ?_assertEqual("<p>! ab:c\na</p>", erlmd:conv("! ab:c\na")),
     ?_assertEqual("<p>` ab:c\na</p>", erlmd:conv("` ab:c\na")),
     ?_assertEqual("<p>\" ab:c\na</p>", erlmd:conv("\" ab:c\na")),
     ?_assertEqual("<p>' ab:c\na</p>", erlmd:conv("' ab:c\na")),
     ?_assertEqual("<p>: ab:c\na</p>", erlmd:conv(": ab:c\na")),
     ?_assertEqual("<p>. ab:c\na</p>", erlmd:conv(". ab:c\na")),
     ?_assertEqual("<p>0 ab:c\na</p>", erlmd:conv("0 ab:c\na")),
     ?_assertEqual("<p>9 ab:c\na</p>", erlmd:conv("9 ab:c\na")),
     ?_assertEqual("<p>8 ab:c\na</p>", erlmd:conv("8 ab:c\na")),
     ?_assertEqual("<p>7 ab:c\na</p>", erlmd:conv("7 ab:c\na")),
     ?_assertEqual("<p>6 ab:c\na</p>", erlmd:conv("6 ab:c\na")),
     ?_assertEqual("<p>5 ab:c\na</p>", erlmd:conv("5 ab:c\na")),
     ?_assertEqual("<p>4 ab:c\na</p>", erlmd:conv("4 ab:c\na")),
     ?_assertEqual("<p>3 ab:c\na</p>", erlmd:conv("3 ab:c\na")),
     ?_assertEqual("<p>2 ab:c\na</p>", erlmd:conv("2 ab:c\na")),
     ?_assertEqual("<p>1 ab:c\na</p>", erlmd:conv("1 ab:c\na")),
     ?_assertEqual("<p>_ ab:c\na</p>", erlmd:conv("_ ab:c\na")),
     ?_assertEqual("<ul>\n<li>ab:c\na</li>\n</ul>", erlmd:conv("* ab:c\na")),
     ?_assertEqual("<ul>\n<li>ab:c\na</li>\n</ul>", erlmd:conv("+ ab:c\na")),
     ?_assertEqual("<blockquote>\n  <p>ab:c\na</p>\n</blockquote>", erlmd:conv("> ab:c\na")),
     ?_assertEqual("<h1>ab:c</h1>\n\n<p>a</p>", erlmd:conv("# ab:c\na")),
     ?_assertEqual("<ul>\n<li>ab:c\na</li>\n</ul>", erlmd:conv("- ab:c\na")),
     ?_assertEqual("<p>= ab:c\na</p>", erlmd:conv("= ab:c\na")),
     ?_assertEqual("<p>/ ab:c\na</p>", erlmd:conv("/ ab:c\na")),
     ?_assertEqual("<p>&lt; /ab:c\na</p>", erlmd:conv("< /ab:c\na")),
     ?_assertEqual("<p>&lt; ab:c\na</p>", erlmd:conv("< ab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv("\r\nab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv("\nab:c\na")),
     ?_assertEqual("<pre><code>ab:c\n</code></pre>\n\n<p>a</p>", erlmd:conv("\tab:c\na")),
     ?_assertEqual("<p>ab:c\na</p>", erlmd:conv(" ab:c\na")),
     ?_assertEqual("<p>(ab:c\na</p>", erlmd:conv("(ab:c\na")),
     ?_assertEqual("<p>]ab:c\na</p>", erlmd:conv("]ab:c\na")),
     ?_assertEqual("<p>[ab:c\na</p>", erlmd:conv("[ab:c\na")),
     ?_assertEqual("<p>)ab:c\na</p>", erlmd:conv(")ab:c\na")),
     ?_assertEqual("<p>(ab:c\na</p>", erlmd:conv("(ab:c\na")),
     ?_assertEqual("<p>/ab:c\na</p>", erlmd:conv("/ab:c\na")),
     ?_assertEqual("<p>\\ab:c\na</p>", erlmd:conv("\\ab:c\na")),
     ?_assertEqual("<p>!ab:c\na</p>", erlmd:conv("!ab:c\na")),
     ?_assertEqual("<p>`ab:c\na</p>", erlmd:conv("`ab:c\na")),
     ?_assertEqual("<p>\"ab:c\na</p>", erlmd:conv("\"ab:c\na")),
     ?_assertEqual("<p>'ab:c\na</p>", erlmd:conv("'ab:c\na")),
     ?_assertEqual("<p>:ab:c\na</p>", erlmd:conv(":ab:c\na")),
     ?_assertEqual("<p>.ab:c\na</p>", erlmd:conv(".ab:c\na")),
     ?_assertEqual("<p>0ab:c\na</p>", erlmd:conv("0ab:c\na")),
     ?_assertEqual("<p>9ab:c\na</p>", erlmd:conv("9ab:c\na")),
     ?_assertEqual("<p>8ab:c\na</p>", erlmd:conv("8ab:c\na")),
     ?_assertEqual("<p>7ab:c\na</p>", erlmd:conv("7ab:c\na")),
     ?_assertEqual("<p>6ab:c\na</p>", erlmd:conv("6ab:c\na")),
     ?_assertEqual("<p>5ab:c\na</p>", erlmd:conv("5ab:c\na")),
     ?_assertEqual("<p>4ab:c\na</p>", erlmd:conv("4ab:c\na")),
     ?_assertEqual("<p>3ab:c\na</p>", erlmd:conv("3ab:c\na")),
     ?_assertEqual("<p>2ab:c\na</p>", erlmd:conv("2ab:c\na")),
     ?_assertEqual("<p>1ab:c\na</p>", erlmd:conv("1ab:c\na")),
     ?_assertEqual("<p>_ab:c\na</p>", erlmd:conv("_ab:c\na")),
     ?_assertEqual("<p>*ab:c\na</p>", erlmd:conv("*ab:c\na")),
     ?_assertEqual("<p>+ab:c\na</p>", erlmd:conv("+ab:c\na")),
     ?_assertEqual("<blockquote>\n  <p>ab:c\na</p>\n</blockquote>", erlmd:conv(">ab:c\na")),
     ?_assertEqual("<h1>ab:c</h1>\n\n<p>a</p>", erlmd:conv("#ab:c\na")),
     ?_assertEqual("<p>-ab:c\na</p>", erlmd:conv("-ab:c\na")),
     ?_assertEqual("<p>=ab:c\na</p>", erlmd:conv("=ab:c\na")),
     ?_assertEqual("<p>/ab:c\na</p>", erlmd:conv("/ab:c\na")),
     ?_assertEqual("<p>Hey\nHo! <br />\nLets Go</p>", erlmd:conv("    \nHey\nHo!  \nLets Go")),
     ?_assertEqual("<p>Hey Ho <br />\nLets Go</p>", erlmd:conv("Hey Ho\t\nLets Go")),
     ?_assertEqual("<p>Hey Ho <br />\nLets Go</p>", erlmd:conv("Hey Ho  \nLets Go")),
     ?_assertEqual("<p>Hey\nHo!\nHardy</p>", erlmd:conv("Hey\nHo!\nHardy\n\n")),
     ?_assertEqual("<p>Hey Ho!\na</p>", erlmd:conv("Hey Ho!\na")),
     ?_assertEqual("<p>3 &lt;4\na</p>", erlmd:conv(" 3 <4\na")),
     ?_assertEqual("<p>3 &lt; 4\na</p>", erlmd:conv(" 3 < 4\na")),
     ?_assertEqual("<p>3 > 4\na</p>", erlmd:conv("3 > 4\na")),
     ?_assertEqual("<p>a\nb\nc</p>", erlmd:conv("a\nb\nc\n \n\t\n     ")),
     ?_assertEqual("<p>a\nb\nc</p>", erlmd:conv("a\nb\nc\n\n\n")),
     ?_assertEqual("", erlmd:conv("  \n")),
     ?_assertEqual("", erlmd:conv("\t\n")),
     ?_assertEqual("", erlmd:conv("\n\n")),
     ?_assertEqual("", erlmd:conv("\n"))
    ].
